// Mocks generated by Mockito 5.4.5 from annotations
// in zonix/test/services/order_service_comprobante_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zonix/features/services/order_service.dart' as _i2;
import 'package:zonix/models/cart_item.dart' as _i4;
import 'package:zonix/models/order.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderService extends _i1.Mock implements _i2.OrderService {
  MockOrderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> createOrder(List<_i4.CartItem>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [items],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Order>> fetchOrders() => (super.noSuchMethod(
        Invocation.method(
          #fetchOrders,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Order>>.value(<_i5.Order>[]),
      ) as _i3.Future<List<_i5.Order>>);

  @override
  _i3.Future<void> uploadComprobante(
    int? orderId,
    String? filePath,
    String? fileType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadComprobante,
          [
            orderId,
            filePath,
            fileType,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> validarComprobante(
    int? orderId,
    String? accion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validarComprobante,
          [
            orderId,
            accion,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
